#!/bin/bash
#=================================================
# File name: init-settings.sh
# Description: This script will be executed during the first boot
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================

# Set default theme to luci-theme-argon
#uci set luci.main.mediaurlbase='/luci-static/argon'

# nikki 需要一些默认配置
# 取消 DNS 重定向
uci delete dhcp.@dnsmasq[0].dns_redirect

# 取消唯一 DHCP 授权
uci delete dhcp.@dnsmasq[0].authoritative
# 取消 lan 动态 DHCP
uci set dhcp.lan.dynamicdhcp='0'

# 禁用 IPv6 https://www.cnblogs.com/NueXini/p/15707858.html
uci delete dhcp.lan.dhcpv6
uci delete dhcp.lan.ra
uci delete dhcp.lan.ra_slaac
uci delete dhcp.lan.ra_flags
uci delete dhcp.lan.max_preferred_lifetime
uci delete dhcp.lan.max_valid_lifetime
uci set dhcp.@dnsmasq[0].filter_aaaa='1'

# 保存到文件
uci commit

#exit 0
